config/routes.rb
Rails.application.routes.draw do
  get 'rewards/myrewards'

  get 'allbiz' => 'staticpages#allbiz'

  resources :rewards
  devise_for :businesses, path: 'businesses'
  root 'staticpages#dashboard'
  get 'dashboard2' => 'staticpages#dashboard2'
  get 'myposts' => 'posts#myposts'
  get 'mycomments' => 'comments#mycomments'  
  resources :syllabuses do
    resources :events
  end
  resources :years
  resources :semesters
  get 'faq' => 'staticpages#faq'
  get 'about' => 'staticpages#about'
  resources :flags
  get 'flagged' => "flags#flagged"
  get 'flag' => "flags#flags"
  resources :hides
  get 'hidden' => "hides#hidden"
  get 'hide' => "hides#hides"
  resources :books do
    member do
      post 'flag'
    end
  end
  resources :subjects
  resources :universities
  devise_for :users, path: 'users'
  resources :courses do
    member do
      post 'enroll'
    end
  end  
  resources :enrolls
  resources :posts do
    resources :comments do
      member do
        put "like",    to:"comments#upvote"
        put "dislike", to:"comments#downvote"
        post 'hide'
      end
    end
    member do
      put "like",    to:"posts#upvote"
      put "dislike", to:"posts#downvote"
      post 'flag'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than_or_equal_to => 0.01}
  has_many :flags
  has_many :users, :through => :flags
end

app/models/business.rb
class Business < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :post
  has_many :hides
  has_many :users, :through => :hides
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :posts
  belongs_to :subject
  belongs_to :university
  has_many :syllabuses
  has_many :enrolls
  has_many :users, :through => :enrolls

  def name_with_univ
  	"#{name}, #{university.name}"
  end
end

app/models/enroll.rb
class Enroll < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :user, uniqueness: { scope: :course,
  message: "Should only enroll once." }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :syllabus
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :book
end

app/models/hide.rb
class Hide < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :course
  belongs_to :user
  has_many :comments, dependent: :nullify
  has_many :flags
  has_many :users, :through => :flags
  validates_format_of :url, :with => /\A^https?+.{1,}\z/i, :allow_blank => true
end
class Post
  def self.highest_voted
    self.order("cached_votes_score DESC")
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :business
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :syllabuses
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :courses
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :semester
  belongs_to :course
  belongs_to :year
  has_many :events
end

app/models/university.rb
class University < ApplicationRecord
  has_many :courses
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :books
  belongs_to :university
  has_many :comments
  acts_as_voter
  has_many :enrolls
  has_many :courses, :through => :enrolls
  has_many :flags
  has_many :posts, :through => :flags
  has_many :hides
  has_many :comments, :through => :hides
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[e]+[d]+[u]\z/i

  
  def increase_karma(count=1)
    update_attribute(:karma, karma + count)
  end
  
  def decrease_karma(count=1)
    update_attribute(:karma, karma - count)
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :years
end

app/controllers/syllabuses_controller.rb
class SyllabusesController < ApplicationController
  before_action :set_syllabus, only: [:show, :edit, :update, :destroy]

  # GET /syllabuses
  # GET /syllabuses.json
  def index
    @syllabuses = Syllabus.all
  end

  # GET /syllabuses/1
  # GET /syllabuses/1.json
  def show
  end

  # GET /syllabuses/new
  def new
    @syllabus = Syllabus.new
  end

  # GET /syllabuses/1/edit
  def edit
  end

  # POST /syllabuses
  # POST /syllabuses.json
  def create
    @syllabus = Syllabus.new(syllabus_params)

    respond_to do |format|
      if @syllabus.save
        format.html { redirect_to @syllabus, notice: 'Syllabus was successfully created.' }
        format.json { render :show, status: :created, location: @syllabus }
      else
        format.html { render :new }
        format.json { render json: @syllabus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /syllabuses/1
  # PATCH/PUT /syllabuses/1.json
  def update
    respond_to do |format|
      if @syllabus.update(syllabus_params)
        format.html { redirect_to @syllabus, notice: 'Syllabus was successfully updated.' }
        format.json { render :show, status: :ok, location: @syllabus }
      else
        format.html { render :edit }
        format.json { render json: @syllabus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /syllabuses/1
  # DELETE /syllabuses/1.json
  def destroy
    @syllabus.destroy
    respond_to do |format|
      format.html { redirect_to syllabuses_url, notice: 'Syllabus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_syllabus
      @syllabus = Syllabus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def syllabus_params
      params.require(:syllabus).permit(:year_id, :course_id, :semester_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/hides_helper.rb
module HidesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/syllabuses_helper.rb
module SyllabusesHelper
end

app/views/syllabuses/_form.html.erb
<%= form_for(syllabus) do |f| %>
  <% if syllabus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(syllabus.errors.count, "error") %> prohibited this syllabus from being saved:</h2>

      <ul>
      <% syllabus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.collection_select :year_id, Year.all, :id, :year %>
  </div>

  <div class="field">
    <%= f.label :semester %><br />
    <%= f.collection_select :semester_id, Semester.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :course %><br />
    <%= f.collection_select :course_id, Course.all, :id, :name_with_univ %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/syllabuses/edit.html.erb
<h1>Editing Syllabus</h1>

<%= render 'form', syllabus: @syllabus %>

<%= link_to 'Show', @syllabus %> |
<%= link_to 'Back', syllabuses_path %>

app/views/syllabuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Syllabuses</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Course</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @syllabuses.each do |syllabus| %>
      <tr>
        <td><%= syllabus.year.year %></td>
        <td><%= syllabus.course.name_with_univ %></td>
        <td><%= syllabus.semester.name %></td>
        <td><%= link_to 'Show', syllabus %></td>
        <td><%= link_to 'Edit', edit_syllabus_path(syllabus) %></td>
        <td><%= link_to 'Destroy', syllabus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Syllabus', new_syllabus_path %>

app/views/syllabuses/new.html.erb
<h1>New Syllabus</h1>

<%= render 'form', syllabus: @syllabus %>

<%= link_to 'Back', syllabuses_path %>

app/views/syllabuses/show.html.erb
<div>
  <p>
    <%= @syllabus.year.year %>
  </p>
  <p>
    <%= @syllabus.semester.name %>
  </p>
  <p>
    <%= @syllabus.course.name %>
  </p>
</div>
<div>
  <h2>Events</h2>
  <%= render @syllabus.events %>
  <h3>Add an event</h3>
  <%= render "events/form" %>
</div>
<%= link_to "Back", root_path %>