config/routes.rb
Rails.application.routes.draw do
  get 'rewards/myrewards'

  get 'allbiz' => 'staticpages#allbiz'

  resources :rewards
  devise_for :businesses, path: 'businesses'
  root 'staticpages#dashboard'
  get 'dashboard2' => 'staticpages#dashboard2'
  get 'myposts' => 'posts#myposts'
  get 'mycomments' => 'comments#mycomments'  
  resources :syllabuses do
    resources :events
  end
  resources :years
  resources :semesters
  get 'faq' => 'staticpages#faq'
  get 'about' => 'staticpages#about'
  resources :flags
  get 'flagged' => "flags#flagged"
  get 'flag' => "flags#flags"
  resources :hides
  get 'hidden' => "hides#hidden"
  get 'hide' => "hides#hides"
  resources :books do
    member do
      post 'flag'
    end
  end
  resources :subjects
  resources :universities
  devise_for :users, path: 'users'
  resources :courses do
    member do
      post 'enroll'
    end
  end  
  resources :enrolls
  resources :posts do
    resources :comments do
      member do
        put "like",    to:"comments#upvote"
        put "dislike", to:"comments#downvote"
        post 'hide'
      end
    end
    member do
      put "like",    to:"posts#upvote"
      put "dislike", to:"posts#downvote"
      post 'flag'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than_or_equal_to => 0.01}
  has_many :flags
  has_many :users, :through => :flags
end

app/models/business.rb
class Business < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :post
  has_many :hides
  has_many :users, :through => :hides
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :posts
  belongs_to :subject
  belongs_to :university
  has_many :syllabuses
  has_many :enrolls
  has_many :users, :through => :enrolls

  def name_with_univ
  	"#{name}, #{university.name}"
  end
end

app/models/enroll.rb
class Enroll < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :user, uniqueness: { scope: :course,
  message: "Should only enroll once." }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :syllabus
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :book
end

app/models/hide.rb
class Hide < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :course
  belongs_to :user
  has_many :comments, dependent: :nullify
  has_many :flags
  has_many :users, :through => :flags
  validates_format_of :url, :with => /\A^https?+.{1,}\z/i, :allow_blank => true
end
class Post
  def self.highest_voted
    self.order("cached_votes_score DESC")
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :business
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :syllabuses
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :courses
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :semester
  belongs_to :course
  belongs_to :year
  has_many :events
end

app/models/university.rb
class University < ApplicationRecord
  has_many :courses
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :books
  belongs_to :university
  has_many :comments
  acts_as_voter
  has_many :enrolls
  has_many :courses, :through => :enrolls
  has_many :flags
  has_many :posts, :through => :flags
  has_many :hides
  has_many :comments, :through => :hides
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[e]+[d]+[u]\z/i

  
  def increase_karma(count=1)
    update_attribute(:karma, karma + count)
  end
  
  def decrease_karma(count=1)
    update_attribute(:karma, karma - count)
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :years
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_business!, :except => [:index, :show]
  before_action :authorized_business, only: [:edit, :update]

  # GET /rewards
  # GET /rewards.json
  def index
    @rewards = Reward.all.paginate(page: params[:page], per_page: 7)
  end

  # GET /myrewards
  def myrewards
    @rewards = Reward.all.where(business: current_business).order("created_at DESC").paginate(page: params[:page], per_page: 7)
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = current_business.rewards.build
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = current_business.rewards.build(reward_params)
    @reward.business = current_business

    respond_to do |format|
      if @reward.save
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to rewards_url, notice: 'Reward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    def authorized_business
      @reward = current_business.rewards.find_by(id: params[:id])
      redirect_to rewards_path, notice: "Not authorized to edit this reward" if @reward.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reward_params
      params.require(:reward).permit(:name, :cost, :description)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/hides_helper.rb
module HidesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/rewards/_form.html.erb
<%= form_for(reward) do |f| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
      <% reward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= link_to 'Back', :back, class: "btn btn-primary pull-left" %>
    <%= f.button :Submit, class: "btn btn-primary btn-fill pull-right" %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', @reward %> |
<%= link_to 'Back', rewards_path %>

app/views/rewards/index.html.erb
<div class="container" style="text-align:center; padding-top:20px; padding-bottom:20px">
  <h1>All Rewards</h1>
</div>

<% if user_signed_in? %>
  <div style="text-align:center">
    <h3>You currently have <%= current_user.try(:karma) %> points.</h3>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th style="text-align: center">Business</th>
        <th style="text-align: center">Name</th>
        <th style="text-align: center">Cost</th>
      </tr>
    </thead>
    <tbody>
      <% @rewards.each do |reward| %>
        <tr>
          <td style="text-align: center"><%= link_to 'Show', reward, :class => 'btn btn-primary btn-round' %></td>
          <td style="text-align: center"><%= reward.business.name %></td>
          <td style="text-align: center"><%= reward.name %></td>
          <td style="text-align: center"><%= reward.cost %> Points</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div style="text-align:center">
  <%= will_paginate @reward %>
</div>

app/views/rewards/myrewards.html.erb
<div class="container">
	<div class="table-responsive">
	  <div class="container-fluid">
	    <h4 style="text-align:center">Our Rewards</h4>
	    <% if @rewards.blank? %>
	      <h5 style="text-align:center">You have not created any rewards yet</h5>
	    <% else %>
	      <table class="table">
	        <thead>
	          <tr>
	            <th>Name</th>
	            <th>Cost</th>
	            <th>Description</th>
	            <th>Time created</th>
	            <th colspan="1"></th>
	          </tr>
	        </thead>

	        <tbody>
	          <% @rewards.each do |reward| %>
	            <tr>
	              <td><%= reward.name %></td>
	              <td><%= reward.cost %></td>
	              <td><%= reward.description %></td>
	              <td><%= time_ago_in_words(reward.created_at) + " ago" %></td>
	              <td><%= link_to 'Show', reward, :class => 'btn btn-primary btn-round' %></td>
	            </tr>
	          <% end %>
	        </tbody>
	      </table>
	    <% end %>
	  </div>
	</div>
	<div style="text-align:center">
	  <%= will_paginate @reward %>
	</div>
</div>

app/views/rewards/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
		<h1>New Reward</h1>
		<%= render 'form', reward: @reward %>
	</div>
  </div>
</div>

app/views/rewards/show.html.erb
<div class="container">
	<h3 style="text-align:center">
	  <strong><%= @reward.name %></strong>
	</h3>

	<p style="text-align:center">
	  <strong>From:</strong>
	  <%= @reward.business.name %> 
	</p>

	<p style="text-align:center">
	  <strong>Cost:</strong>
	  <%= @reward.cost %> Points
	</p>

	<p style="text-align:center">
	  <strong>Description:</strong>
	  <%= @reward.description %>
	</p>
	<div style="text-align:center">
		<%= link_to 'Edit', edit_reward_path(@reward) %> |
		<%= link_to 'Back', :back %>
	</div>
</div>