config/routes.rb
Rails.application.routes.draw do
  get 'rewards/myrewards'

  get 'allbiz' => 'staticpages#allbiz'

  resources :rewards
  devise_for :businesses, path: 'businesses'
  root 'staticpages#dashboard'
  get 'dashboard2' => 'staticpages#dashboard2'
  get 'myposts' => 'posts#myposts'
  get 'mycomments' => 'comments#mycomments'  
  resources :syllabuses do
    resources :events
  end
  resources :years
  resources :semesters
  get 'faq' => 'staticpages#faq'
  get 'about' => 'staticpages#about'
  resources :flags
  get 'flagged' => "flags#flagged"
  get 'flag' => "flags#flags"
  resources :hides
  get 'hidden' => "hides#hidden"
  get 'hide' => "hides#hides"
  resources :books do
    member do
      post 'flag'
    end
  end
  resources :subjects
  resources :universities
  devise_for :users, path: 'users'
  resources :courses do
    member do
      post 'enroll'
    end
  end  
  resources :enrolls
  resources :posts do
    resources :comments do
      member do
        put "like",    to:"comments#upvote"
        put "dislike", to:"comments#downvote"
        post 'hide'
      end
    end
    member do
      put "like",    to:"posts#upvote"
      put "dislike", to:"posts#downvote"
      post 'flag'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than_or_equal_to => 0.01}
  has_many :flags
  has_many :users, :through => :flags
end

app/models/business.rb
class Business < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :post
  has_many :hides
  has_many :users, :through => :hides
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :posts
  belongs_to :subject
  belongs_to :university
  has_many :syllabuses
  has_many :enrolls
  has_many :users, :through => :enrolls

  def name_with_univ
  	"#{name}, #{university.name}"
  end
end

app/models/enroll.rb
class Enroll < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :user, uniqueness: { scope: :course,
  message: "Should only enroll once." }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :syllabus
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :book
end

app/models/hide.rb
class Hide < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :course
  belongs_to :user
  has_many :comments, dependent: :nullify
  has_many :flags
  has_many :users, :through => :flags
  validates_format_of :url, :with => /\A^https?+.{1,}\z/i, :allow_blank => true
end
class Post
  def self.highest_voted
    self.order("cached_votes_score DESC")
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :business
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :syllabuses
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :courses
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :semester
  belongs_to :course
  belongs_to :year
  has_many :events
end

app/models/university.rb
class University < ApplicationRecord
  has_many :courses
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :books
  belongs_to :university
  has_many :comments
  acts_as_voter
  has_many :enrolls
  has_many :courses, :through => :enrolls
  has_many :flags
  has_many :posts, :through => :flags
  has_many :hides
  has_many :comments, :through => :hides
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[e]+[d]+[u]\z/i

  
  def increase_karma(count=1)
    update_attribute(:karma, karma + count)
  end
  
  def decrease_karma(count=1)
    update_attribute(:karma, karma - count)
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :years
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def about
  end
  
  def faq
  end

  def dashboard
  	if user_signed_in?
	  	@enrolls = Enroll.all.where(user: current_user)
	  	@posts = Post.all
      @myposts = Post.all.where(user: current_user).paginate(page: params[:page], per_page: 7)
      @comments = Comment.all
      @mycomments = Comment.all.where(user: current_user).paginate(page: params[:page], per_page: 7)
      #@rewards = Reward.all
      #@myrewards = Reward.all.where(user: current_user)
    elsif business_signed_in?
      @rewards = Reward.all
      @myrewards = Reward.all.where(business: current_business).paginate(page: params[:page], per_page: 7)
    else
      @search = Post.ransack(params[:q])
      @posts = @search.result.includes(:comments)
	  end
  end

  def allbiz
    @businesses = Business.all
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/hides_helper.rb
module HidesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/staticpages/about.html.erb
<h1>Staticpages#about</h1>
<p>Find me in app/views/staticpages/about.html.erb</p>

app/views/staticpages/allbiz.html.erb
<div class="container">
	<h1>All Businesses</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>

    <tbody>
      <% @businesses.each do |business| %>
        <tr>
          <td><%= business.name %></td>
          <td><%= business.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/staticpages/dashboard.html.erb
  <% if user_signed_in? %>
  <div class="container" style="text-align:center; padding-top:; padding-bottom:">
    <h1>Dashboard</h1>
  </div>
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <h4 class="title">My Courses</h2>
          <% if @enrolls.blank? %>
            <h5 style= "text-align:center">You haven't signed up for any courses yet.</h5>
            <p style= "text-align:center"><%= link_to 'Courses', courses_path, class: "btn btn-primary btn-round btn-fill" %></p>
          <% else %>
          <% @enrolls.each do |enroll| %>
            <div class="card container-fluid">
                <div class="header">
                    <h4 class="title"><%= enroll.course.try(:name) %></h4>
                    <p class="category"><div class="btn-group"><%= link_to 'Course Page', course_path(enroll.course), :class => 'btn btn-primary' %><%= link_to 'Unenroll', enroll, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></div></p>
                </div>
                <div class="content">
                    <%= enroll.course.posts.count %> posts
                    <%= enroll.course.enrolls.count %> enrolls
                </div>
            </div>
          <% end %>
          <% end %>
        </div>
        <div class="col-md-6">
          <div class="table-responsive">
            <div class="container-fluid">
              <h4 class="title">My Posts</h4>

                <% if @posts.blank? %>
                <h5 style= "text-align:center">You haven't made any posts yet.</h2>
                <p style= "text-align:center"><%= link_to 'New Post', new_post_path, class: "btn btn-primary btn-round btn-fill" %></p>
                <% else %>

              <table class="table">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Course</th>
                    <th>Post Karma</th>
                    <th>Time created</th>
                    <th colspan="1"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @myposts.each do |post| %>
                    <tr>
                      <td><%= post.title %></td>
                      <td><%= post.course.name %></td>
                      <td><%= post.get_upvotes.size %> - <%= post.get_downvotes.size %> = <%= post.weighted_score %> </td>
                      <td><%= time_ago_in_words(post.created_at) + " ago" %></td>
                      <td><%= link_to 'Show', post, :class => 'btn btn-primary btn-round' %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <% end %>
            </div>
          </div>
          <div style="text-align:center">
            <%= will_paginate @myposts %>
          </div>
          <div class="table-responsive">
            <div class="container-fluid">
              <h4 class="title">My Comments</h1>
              <% if @comments.blank? %>
                <h5 style= "text-align:center">You haven't made any comments yet.</h5>
              <% else %>
              <table class="table">
                <thead>
                  <tr>
                    <th>Post</th>
                    <th>Content</th>
                    <th>Comment Karma</th>
                    <th>Time created</th>
                    <th colspan="1"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @mycomments.each do |comment| %>
                    <tr>
                      <td><%= comment.post.title %></td>
                      <td><%= comment.content %></td>
                      <td><%= comment.get_upvotes.size %> - <%= comment.get_downvotes.size %> = <%= comment.weighted_score %> </td>
                      <td><%= time_ago_in_words(comment.created_at) + " ago" %></td>
                      <td><%= link_to 'Show', comment.post, :class => 'btn btn-primary btn-round' %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <% end %>
            </div>
          </div>
          <div style="text-align:center">
            <%= will_paginate @mycomments %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% elsif business_signed_in? %>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h4 style="text-align:center">Business Name: <strong><%= current_business.name %></strong></h4>
        <div style="text-align:center">
          <button class="btn btn-primary btn-round" data-toggle="modal" data-target="#myModal">
            Our business reward code
          </button>
          <br><br>
          <%= link_to 'New Reward', new_reward_path, :class => "btn btn-round btn-primary btn-fill" %>
        </div>
        <br>

        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Our code</h4>
              </div>
              <div class="modal-body" style="text-align:center">
                <%= current_business.code %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default btn-simple" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="table-responsive">
          <div class="container-fluid">
            <h4 style="text-align:center">Our Rewards</h4>
            <% if @rewards.blank? %>
              <h5>You have not created any rewards yet</h5>
            <% else %>
              <table class="table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Cost</th>
                    <th>Description</th>
                    <th>Time created</th>
                    <th colspan="1"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @myrewards.each do |reward| %>
                    <tr>
                      <td><%= reward.name %></td>
                      <td><%= reward.cost %></td>
                      <td><%= reward.description %></td>
                      <td><%= time_ago_in_words(reward.created_at) + " ago" %></td>
                      <td><%= link_to 'Show', reward, :class => 'btn btn-primary btn-round' %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% end %>
          </div>
        </div>
        <div style="text-align:center">
        <%= link_to 'All my rewards', rewards_myrewards_path, class: "btn btn-primary btn-round" %>
        </div>
      </div>

    </div>
  </div>
  <% else %>
  <div class="wrapper">
    <div class="container" style="text-align:center; padding-top:20px; padding-bottom:20px">
      <h1>Welcome to Skoosm!</h1>
    </div>
     <br>
     <div class="container">
         <div class="row">
              <div class="col-md-6">
                 <h5>Shoulders of Giants</h5>
                 <p>
                     Isaac Newton once said "If I have seen further than others, it is by standing on the shoulders of giants." You are not the first person to have struggled with this problem for this class and you will not be the last. Skoosm is a place where studnets can find the answers to their problems and help others with theirs as well.</p>
                  <p>
                    Make sure to sign up and browse around for anything that may help with your classes or help others and recieve rewards. </p>
             </div>
             <div class="col-md-6">
                <div class="img-container">
                    <img src="../assets/img/thumb.jpg" alt="..." />
                </div>
             </div>
          </div>
     </div>
     <div class="space-50"></div>
       <div class="social-line">
           <div class="container">
              <div class="row">
                   <div class="col-sm-3">
                       <a href="" class="btn btn-round btn-fill btn-social btn-facebook">
                           <i class="fa fa-facebook-square"></i> Facebook
                       </a>
                   </div>
                    <div class="col-sm-3">
                       <a href="" class="btn btn-round btn-fill btn-social btn-twitter">
                           <i class="fa fa-twitter"></i> Twitter
                       </a>
                   </div>
                    <div class="col-sm-3">
                       <a href="" class="btn btn-round btn-fill btn-social btn-google">
                           <i class="fa fa-google-plus-square"></i> Google+
                       </a>
                   </div>
                   <div class="col-sm-3">
                       <a href="" class="btn btn-round btn-fill btn-social btn-reddit">
                           <i class="fa fa-reddit"></i> Reddit
                       </a>
                   </div>
              </div>
           </div>
       </div>
  </div> <!-- wrapper -->
  <% end %>

app/views/staticpages/faq.html.erb
<h1>Staticpages#faq</h1>
<p>Find me in app/views/staticpages/faq.html.erb</p>