config/routes.rb
Rails.application.routes.draw do
  get 'rewards/myrewards'

  get 'allbiz' => 'staticpages#allbiz'

  resources :rewards
  devise_for :businesses, path: 'businesses'
  root 'staticpages#dashboard'
  get 'dashboard2' => 'staticpages#dashboard2'
  get 'myposts' => 'posts#myposts'
  get 'mycomments' => 'comments#mycomments'  
  resources :syllabuses do
    resources :events
  end
  resources :years
  resources :semesters
  get 'faq' => 'staticpages#faq'
  get 'about' => 'staticpages#about'
  resources :flags
  get 'flagged' => "flags#flagged"
  get 'flag' => "flags#flags"
  resources :hides
  get 'hidden' => "hides#hidden"
  get 'hide' => "hides#hides"
  resources :books do
    member do
      post 'flag'
    end
  end
  resources :subjects
  resources :universities
  devise_for :users, path: 'users'
  resources :courses do
    member do
      post 'enroll'
    end
  end  
  resources :enrolls
  resources :posts do
    resources :comments do
      member do
        put "like",    to:"comments#upvote"
        put "dislike", to:"comments#downvote"
        post 'hide'
      end
    end
    member do
      put "like",    to:"posts#upvote"
      put "dislike", to:"posts#downvote"
      post 'flag'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ }, :numericality => {:greater_than_or_equal_to => 0.01}
  has_many :flags
  has_many :users, :through => :flags
end

app/models/business.rb
class Business < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rewards
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :post
  has_many :hides
  has_many :users, :through => :hides
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :posts
  belongs_to :subject
  belongs_to :university
  has_many :syllabuses
  has_many :enrolls
  has_many :users, :through => :enrolls

  def name_with_univ
  	"#{name}, #{university.name}"
  end
end

app/models/enroll.rb
class Enroll < ApplicationRecord
  belongs_to :course
  belongs_to :user
  validates :user, uniqueness: { scope: :course,
  message: "Should only enroll once." }
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :syllabus
end

app/models/flag.rb
class Flag < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :book
end

app/models/hide.rb
class Hide < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :course
  belongs_to :user
  has_many :comments, dependent: :nullify
  has_many :flags
  has_many :users, :through => :flags
  validates_format_of :url, :with => /\A^https?+.{1,}\z/i, :allow_blank => true
end
class Post
  def self.highest_voted
    self.order("cached_votes_score DESC")
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :business
end

app/models/semester.rb
class Semester < ApplicationRecord
  has_many :syllabuses
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :courses
end

app/models/syllabus.rb
class Syllabus < ApplicationRecord
  belongs_to :semester
  belongs_to :course
  belongs_to :year
  has_many :events
end

app/models/university.rb
class University < ApplicationRecord
  has_many :courses
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :books
  belongs_to :university
  has_many :comments
  acts_as_voter
  has_many :enrolls
  has_many :courses, :through => :enrolls
  has_many :flags
  has_many :posts, :through => :flags
  has_many :hides
  has_many :comments, :through => :hides
  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[e]+[d]+[u]\z/i

  
  def increase_karma(count=1)
    update_attribute(:karma, karma + count)
  end
  
  def decrease_karma(count=1)
    update_attribute(:karma, karma - count)
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :years
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :authorized_user, only: [:edit, :update]

  # GET /myposts
  # GET /myposts.json
  def myposts
    @posts = Post.all.where(user: current_user).order("created_at DESC").paginate(page: params[:page], per_page: 7)
  end
  
  # GET /posts
  # GET /posts.json
  def index
    @search = Post.ransack(params[:q])
    @posts = @search.result.highest_voted.includes(:comments).where.not(id: Flag.select(:post_id)).paginate(page: params[:page], per_page: 7)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    if current_user.voted_up_on? @post
      redirect_to :back
    elsif current_user.voted_down_on? @post
      @post.upvote_by current_user
      @post.user.increase_karma
      @post.user.increase_karma
      redirect_to :back      
    else
      @post.upvote_by current_user
      @post.user.increase_karma
      redirect_to :back
    end
  end
  
  def downvote
    @post = Post.find(params[:id])
    if current_user.voted_down_on? @post
      redirect_to :back
    elsif current_user.voted_up_on? @post
      @post.downvote_by current_user
      @post.user.decrease_karma
      @post.user.decrease_karma
      redirect_to :back
    else
      @post.downvote_by current_user
      @post.user.decrease_karma
      redirect_to :back
    end
  end

  # POST /flags
  # POST /flags.json
  def flag
    @post = Post.find(params[:id])
    @flag = @post.flags.create(params.permit(:post_id,:user_id))
    @flag.user_id = current_user.id
    
      respond_to do |format|
        if @flag.save
          format.html { redirect_to posts_url, notice: 'Flag was successfully created.' }
          format.json { render json: @flag, status: :created, location: @flag }
        else
          format.html { redirect_to posts_url}
          format.json { render json: @flag.errors, status: :unprocessable_entity }
        end
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def authorized_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to posts_path, notice: "Not authorized to edit this post" if @post.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :url, :content, :course_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/hides_helper.rb
module HidesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course %><br />
    <%= f.collection_select :course_id, Course.all, :id, :name_with_univ, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= link_to 'Back', :back, class: "btn btn-primary pull-left" %>
    <%= f.button :Submit, class: "btn btn-primary btn-fill pull-right" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container" style="text-align:center; padding-top:20px; padding-bottom:20px">
  <h1>All posts</h1>
</div>
 <div class="container">
   <%= search_form_for @search, defaults: {wrapper: :inline_field4} do |f| %>
     <div class="container">
        <div class="row" style="text-align:center">
             <div class="col-md-offset-2 col-md-6">
                <form class="">
                     <div class="form-group">
                          <%= f.text_field :title_or_content_or_comments_content_cont, placeholder: 'Search our posts', :class => 'form-control' %>
                     </div>
                 </form>
             </div>
             <div class="col-md-2">
                <%= f.submit "Search", :class => 'btn btn-primary btn-fill btn-block' %>
             </div>
        </div>
     </div>
   <% end %>
 </div>
 <br>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th style="text-align: center">Title</th>
        <th style="text-align: center">Course</th>
        <th style="text-align: center">University</th>
        <th style="text-align: center">Post Karma</th>
        <th style="text-align: center">User(karma)</th>
        <th style="text-align: center">Like</th>
        <th style="text-align: center">Dislike</th>
        <th style="text-align: center">Time created</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td style="text-align: center"><%= link_to 'Show', post, :class => 'btn btn-primary btn-round' %></td>
          <td style="text-align: center"><%= post.title %></td>
          <td style="text-align: center"><%= post.course.name %></td>
          <td style="text-align: center"><%= post.course.university.name %></td>
          <% if post.user.blank? %>
              <td style="text-align: center">N/A</td>
              <td style="text-align: center">User Deleted</td>
              <td style="text-align: center">N/A</td>
              <td style="text-align: center">N/A</td>
            <% else %>
              <td style="text-align: center"><%= post.get_upvotes.size %> - <%= post.get_downvotes.size %> = <%= post.weighted_score %> </td>
              <td style="text-align: center"><%= post.user.email %>(<%= post.user.try(:karma) %>)</td>
              <td class="td-actions text-center"><%= link_to like_post_path(post), method: :put do %>
                <span class="pe-7s-up-arrow" style="font-size: 20pt"></span><% end %></td>
              <td class="td-actions text-center"><%= link_to dislike_post_path(post), method: :put do %>
                <span class="pe-7s-bottom-arrow" style="font-size: 20pt"></span><% end %></td>
          <% end %>
          <td style="text-align: center"><%= time_ago_in_words(post.created_at) + " ago" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div style="text-align:center">
  <%= will_paginate @post %>
</div>

app/views/posts/myposts.html.erb
<h1>My Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Content</th>
      <th>Course</th>
      <th>Subject</th>
      <th>User</th>
      <th>User Karma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.url %></td>
        <td><%= post.content %></td>
        <td><%= post.course.name %></td>
        <td><%= post.course.subject.name %></td>
        <% if post.user.blank? %>
            <td>User Deleted</td>
            <td>N/A</td>
          <% else %>
            <td><%= post.user.email %></td>
            <td><%= post.user.try(:karma) %></td>
            <td><%= link_to like_post_path(post), method: :put do %>upvote<% end %><%= post.get_upvotes.size %></td>
            <td><%= link_to dislike_post_path(post), method: :put do %>downvote<% end %><%= post.get_downvotes.size %></td>
        <% end %>
        <td><%= link_to 'Show', post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6">
		<h1>New Post</h1>
		<%= render 'form', post: @post %>
	</div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <h3 style="text-align:center">
      <%= @post.title %>
    </h3>
    <p style="text-align:center">
      By: <%= @post.user.email %>(<%= @post.user.try(:karma) %>)
    </p>
    <p style="text-align:center">
      <%= time_ago_in_words(@post.created_at) + " ago" %>
    </p>
    <% if @post.url.blank? %>
    <% else %>
    <p style="text-align:center">
      <%= link_to @post.url, @post.url, :target => "_blank" %>
    </p>
    <% end %>

  </div>
</div>

<div class="container" style="padding-top:70px">
 <div class="row">
    <div class="col-md-8 bottom-border">
      <h1 class="title title-blog"></h1><h3></h3>
      <p><%= @post.content %></p>
      <br>
      <br>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <div class="social-buttons">
        <p style="text-align: center">Points: <%= @post.get_upvotes.size %> - <%= @post.get_downvotes.size %> = <%= @post.weighted_score %></p>
    </div>

    <p style="text-align:center">
      <%= @post.course.name %>
    </p>

    <div style="text-align:center">
      <% if @post.user == current_user %>
      <td><%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-info btn-round' %></td>
      <td><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-round' %></td>
      <% end %>
      <br>
      <br>
      <%= link_to 'Back', :back, :class => 'btn btn-default btn-round' %>
      <%= link_to 'Flag', flag_post_path(@post), method: :post, :class => 'btn btn-warning btn-round' %>
    </div>
  </div>
 </div>
 <div class="section">
  <div class="container container-comments">
    <h3 class="title" style="text-align:center">Comments</h3>
    <div class="row" style="">
      <div class="col-md-8 ">
          <div class="media-area">
              <div class="media">
                <div class="media-body">
                  <%= render :partial => @post.comments.where.not(id: Hide.select(:comment_id)) %>
                </div>
              </div> 
              <!--  Comment  -->
            <%= render "comments/form" %>
          </div> 
      </div> <!-- end col-md-8 -->
    </div>
  </div>
 </div>
</div>